export const PROJECT_PIN_TOGGLE_BY_ID = 'PROJECT_PIN_TOGGLE_BY_ID'
export const TASK_PIN_TOGGLE_BY_ID = 'TASK_PIN_TOGGLE_BY_ID'
export const TASK_TOGGLE_BY_ID = 'TASK_TOGGLE_BY_ID'
export const TASK_HIDDEN_ALL = 'TASK_HIDDEN_ALL'
